#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DSHS.DCS.Droid.Resource", IsApplication=true)]

namespace DSHS.DCS.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int LoadingAnimation = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accounts = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BackgroundShape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BackgroundStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int contacts = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DCSIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DSHSICON = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int leads = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Location = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int MainIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settings = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int SplashLogo = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int SplashLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
